version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks: 
    - postgresql_net
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=your-db-password
      - POSTGRESQL_DATABASE=dev
  pgadmin: 
    image: docker.io/dpage/pgadmin4
    ports: 
    - '8880:80'
    networks:
    - postgresql_net
    environment: 
      - PGADMIN_DEFAULT_EMAIL=your-email
      - PGADMIN_DEFAULT_PASSWORD=your-admin-password
volumes:
  postgresql_data:
    driver: local
networks:
  postgresql_net: